# -*- coding: utf-8 -*-
"""Command line project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16LMrsUf_Fm31ggUWTc8JNQPq8e5krxrN
"""


import cv2
import urllib.request
from pychubby.actions import Multiple, Smile ,StretchNostrils , OpenEyes , Lambda
from pychubby.detect import LandmarkFace
import argparse


def parse_opt(known=False):

  parser = argparse.ArgumentParser()
  parser.add_argument('--input_path', type=str, default='bahram.jpg')
  parser.add_argument('--threshold', type=float, default=0.1)
  opt = parser.parse_known_args()[0] if known else parser.parse_args()
  return opt

def main(opt):

  img_path = opt.input_path
  img = cv2.imread(img_path)
  img = cv2.cvtColor(img , cv2.COLOR_BGR2RGB)
  # thereshold = float(input( "enter the threshold"))
  lf = LandmarkFace.estimate(img)


  # make 10 percent nose smaller
  n = Multiple(StretchNostrils(-opt.threshold))
  # make 10 percent left eye smaller
  left_eye = Multiple(Lambda(opt.threshold , specs={"OUTER_EYE_LID_R": (80, 0.5)}))
  # for the nose
  lf_new,_ = n.perform(lf)
  # for the left eye
  lf_new,_ = left_eye.perform(lf_new)

  lf_new.plot(show_numbers=False)
 

if __name__=="__main__":

  opt = parse_opt()
  main(opt)

